language: python
dist: xenial
os: linux
install:
  - sudo apt-get update
  - pip install coveralls==2.0.0 tox-travis==0.12
jobs:
  include:
  - name: 'Python 3.6'
    python: 3.6
  - name: 'Python 3.7'
    python: 3.7
  - name: 'Python 3.8'
    python: 3.8
script: tox
after_success: if [ "${TRAVIS_PYTHON_VERSION}" == "3.7" ]; then coveralls; fi;
